static json for PSC to OVM translation
cesko-digital/nedluzimstatu pull request #59
Opened 2021-03-03 11:49 UTC by stefanides

první část - přidání jsonu s PSČ

2021-03-03 16:09 UTC, martinwenisch approved these changes
Otestoval jsem to na forku:
https://github.com/martinwenisch/nedluzimstatu

Funguje to bez problemu. Vysledny test-deployment zde:
http://test-nedluzimstatu-pr1.s3-website-eu-west-1.amazonaws.com

Injectnuty public soubor zde:
http://test-nedluzimstatu-pr1.s3-website-eu-west-1.amazonaws.com/psc2ovm/psc_obce_2021.json

@miiila Poprosil bych te o review, aby si vedel jak ten mechanismus pridavani dalsiho statickeho obsahu do deploymentu funguje. Diky

2021-03-03 17:11 UTC, miiila commented
@martinwenisch dík, vypadá to srozumitelně. Jenom teda - když se aktualizuje pouze `public`, tak se deploy neprovede. Bude to potřeba udělat buď ručně nebo vynutit nějakou změnu ve `static_content/**`. Nebylo by lepší mít vlastní GH akci na sync public složky?

2021-03-03 17:16 UTC, martinwenisch commented
@miiila Dobra poznamka, pridejme prosim tu cestu `- 'public/**'` do paths blocku te same akce.

A kdyz uz jsme u optimalizaci, nechceme cp celou public slozku? Je to na tobe, takhle by to bylo pripravene pro budouci rozsireni. Kdyby nekdo chtel pridavat dalsi static data.

2021-03-03 17:34 UTC, miiila commented
@martinwenisch Nevím, jestli to chápu správně, ale jde jen o to, jsetli bude pak v cestě public nebo ne? Já bych byl pro, ať je v tom pořádek, ale moc nerozumím tomu, proč to tam původně leželo jen tak :-)

2021-03-03 17:38 UTC, martinwenisch requested changes
Sem si ten approval rozmyslel. Muzeme udelat 2 upravy, prosim?

1. Pridat `- 'public/**'` do paths nahore. At se akce spousti pri zmene jak static_content, tak public slozky.
2. Kopirovat celou slozku public, ne jen public/psc2ovm

Diky

2021-03-03 17:42 UTC, miiila commented
@stefanides Uděláš to nebo to mám udělat já? Nechci ti zbytečně zasahovat do Pull Requestu :-)

2021-03-05 09:45 UTC, stefanides commented
Udělám to, jen ještě přemýšlím nad tím automatickým deploy - pokud tam přidám i kus js, pak může být potřeba udržet sychronizaci mezi /public a /static_content z wordpressu, aby to společně fungovalo. tj. není lepší deploy spouštět jen z WP? nebo naopak do /public dávat víc verzí současně a WP si vybere tu správnou?

2021-03-05 10:02 UTC, miiila commented
@stefanides Nevím, jestli to chápu správně, ale v public by ideálně žádný fungující js být neměl, ne? Čekal bych, že to bude jen zdroj dat a samotná funkcionalita bude implementována jinde a bude se na tahle data jen dotazovat.

Nebo je plán jiný?

2021-03-05 10:13 UTC, stefanides commented
@miiila i data můžou potřebovat verzi, když se změní. A aby to fungovalo i z testu, potřebuju tady min. kousek javascriptu, který data stáhne (nebo tam nějak tlačit CORS). plus ten js není úplně triviální - a přišlo mi o něco lepší mít jej v gitu tady s komentářema než ve WP (ale není to nutné, WP jej zvládne taky)

2021-03-06 11:51 UTC, miiila commented
@stefanides už rozumím. A nevím :-) Asi mi chybí dostatečný kontext, jak to má celé fungovat. Data doufám verzovat nepotřebujeme - snad by nám mohla stačit jedna aktuální verze.

Navrhoval bych teď pro odblokování udělat ty dva kroky, co navrhuje Martin a pak se nad tím zamyslet.

cc @martinwenisch, jestli máš nějaký kontext, názor nebo jsi měl nějakou vizi, jak by to mělo fungovat. Já se ještě zcela nechytl :-)

2021-03-06 12:47 UTC, martinwenisch commented
@miiila Moje vize, kdyz sem tenhle deployment stavel byla ciste mit moznost "mergovat" do produkce dalsi staticke komponenty, toz tenhle postup naplnuje. Jak si to budete spravovat, jestli to chcete verzovat, co tam budete davat ... je ciste na vas. 

Jakakoli varianta funguje, jen je potreba to nejak zdokumentovat v readme.

2021-03-06 20:33 UTC, stefanides commented
ok, připravím jednoduchou verzi + komentář do dokumentace - a uvidíme :)

2021-03-08 20:32 UTC, miiila approved these changes

2021-03-08 21:30 UTC, martinwenisch approved these changes

2021-03-22 08:51 UTC, merged